### ISSUE TITLE
What if the CSP directive is dictated from within an iframe? How should we behave? 

### ISSUE THREAD

**Issue by weizman** [WICG/Realms-Initialization-Control#14]

**Comment by mhofman** [comment]
IMO the directive should only apply where current CSP directives apply, aka same origin realms covered by the [same policy containers](https://github.com/whatwg/html/issues/4926): about:blank and co, but not same origin iframes covered by their own CSP.

**Comment by weizman** [comment]
After discussing with @yoavweiss , not allowing RIC set from non top realms is fine (as the explainer already states)

**Comment by weizman** [comment]
I sympathize with the concerns suggested by your question, we are currently doing some homework regarding whether that's the case and if that changes how well CSP is positioned to accomplish our goal.

I'm leaving this as closed because the wondering around CSP is being worked on at #10.
